name: Doltpy Tests

on: push

jobs:
  # Run test suite across all major OS types
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python_version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        sudo curl -L https://github.com/liquidata-inc/dolt/releases/latest/download/install.sh | sudo bash
        dolt config --global --add user.email bojack@horseman.com
        dolt config --global --add user.name "Bojack Horseman"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute pytest
      run: |
        pytest -m 'not sql_sync'
    - name: Discord Notify
      if: always()
      uses: dolthub/ga-discord-notify@master
      with:
        job-status: ${{ job.status }}
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        notify-on-success: false
