name: Publish to PyPi

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Build from source
      run: |
        python setup.py sdist
    - name: Publish Doltpy to PyPI
      # uses: pypa/gh-action-pypi-publish@master
      # with:
      #   user: DoltHub
      #   password: ${{ secrets.pypi_password }}
      run: |
        echo "Test process"

  notify:
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      # GITHUB_REF is expected to be set in the format refs/tags/0.3.1
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
    - name: Discord Notification
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        username: GhostOfOctacat
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: "${{format('Doltpy {0}', steps.get_version.outputs.VERSION)}} pushed to PyPi"
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
