name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.23.4'
        required: true

jobs:

  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump Version
        uses: dolthub/ga-bump-version@master
        with:
          version-string: ${{ github.event.inputs.version }}
          version-file: setup.py
      - name: Discord Notify
        if: always()
        uses: dolthub/ga-discord-notify@test-github-context
        with:
          job-status: ${{ job.status }}
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          notify-on-success: false

  publish:
    needs: bump-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.9']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout release
      run: |
        git fetch --tags --all
        git checkout tags/v${{ github.event.inputs.version }} -b v${{ github.event.inputs.version }}
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Build from source
      run: |
        python setup.py sdist
    - name: Publish Doltpy to PyPI
      # uses: pypa/gh-action-pypi-publish@master
      # with:
      #   user: DoltHub
      #   password: ${{ secrets.pypi_password }}
      run: |
        echo "Test process"
    - name: Discord Notify
      if: always()
      uses: dolthub/ga-discord-notify@test-github-context
      with:
        job-status: ${{ job.status }}
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        notify-on-success: false
