name: Release Notification

on: release

jobs:
  notify:
    name: Release Notification
    steps:
      - name: Send Discord Notification
        uses: dolthub/ga-discord-notify@master
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          notify-on-success: true
